# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvisUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainUI(object):
    def setupUi(self, mainUI):
        mainUI.setObjectName("mainUI")
        mainUI.resize(1320, 732)
        self.centralwidget = QtWidgets.QWidget(mainUI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1361, 751))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D://jarvis 2.0//Black_Template.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gif_1 = QtWidgets.QLabel(self.centralwidget)
        self.gif_1.setGeometry(QtCore.QRect(-10, -10, 681, 741))
        self.gif_1.setText("")
        self.gif_1.setPixmap(QtGui.QPixmap("D://jarvis 2.0//Iron_Template_1.gif"))
        self.gif_1.setScaledContents(True)
        self.gif_1.setObjectName("gif_1")

        
        self.gif_2 = QtWidgets.QLabel(self.centralwidget)
        self.gif_2.setGeometry(QtCore.QRect(670, 10, 511, 391))
        self.gif_2.setText("")
        self.gif_2.setPixmap(QtGui.QPixmap("D://jarvis 2.0//__1.gif"))
        self.gif_2.setScaledContents(True)
        self.gif_2.setObjectName("gif_2")
        self.yt_push = QtWidgets.QPushButton(self.centralwidget)
        self.yt_push.setGeometry(QtCore.QRect(640, 470, 101, 41))
        self.yt_push.setStyleSheet("background-color: rgb(0, 118, 177);\n"
"font: 75 18pt \"Agency FB\";")
        self.yt_push.setObjectName("yt_push")
        self.chrome_push = QtWidgets.QPushButton(self.centralwidget)
        self.chrome_push.setGeometry(QtCore.QRect(760, 470, 101, 41))
        self.chrome_push.setStyleSheet("background-color: rgb(0, 118, 177);\n"
"font: 75 18pt \"Agency FB\";")
        self.chrome_push.setObjectName("chrome_push")
        self.word_push = QtWidgets.QPushButton(self.centralwidget)
        self.word_push.setGeometry(QtCore.QRect(880, 470, 101, 41))
        self.word_push.setStyleSheet("background-color: rgb(0, 118, 177);\n"
"font: 75 18pt \"Agency FB\";")
        self.word_push.setObjectName("word_push")
        self.power_push = QtWidgets.QPushButton(self.centralwidget)
        self.power_push.setGeometry(QtCore.QRect(1000, 470, 101, 41))
        self.power_push.setStyleSheet("background-color: rgb(0, 118, 177);\n"
"font: 75 18pt \"Agency FB\";")
        self.power_push.setObjectName("power_push")
        self.excel_push = QtWidgets.QPushButton(self.centralwidget)
        self.excel_push.setGeometry(QtCore.QRect(1120, 470, 101, 41))
        self.excel_push.setStyleSheet("background-color: rgb(0, 118, 177);\n"
"font: 75 18pt \"Agency FB\";")
        self.excel_push.setObjectName("excel_push")
        self.start_push = QtWidgets.QPushButton(self.centralwidget)
        self.start_push.setGeometry(QtCore.QRect(790, 630, 101, 41))
        self.start_push.setStyleSheet("background-color: rgb(231, 231, 0);\n"
"font: 75 18pt \"Agency FB\";")
        self.start_push.setObjectName("start_push")
        self.close_push = QtWidgets.QPushButton(self.centralwidget)
        self.close_push.setGeometry(QtCore.QRect(910, 630, 101, 41))
        self.close_push.setStyleSheet("background-color: rgb(207, 0, 0);\n"
"font: 75 18pt \"Agency FB\";")
        self.close_push.setObjectName("close_push")
        self.whatsapp_push = QtWidgets.QPushButton(self.centralwidget)
        self.whatsapp_push.setGeometry(QtCore.QRect(850, 560, 101, 41))
        self.whatsapp_push.setStyleSheet("background-color: rgb(0, 118, 177);\n"
"font: 75 18pt \"Agency FB\";")
        self.whatsapp_push.setObjectName("whatsapp_push")
        mainUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainUI)
        QtCore.QMetaObject.connectSlotsByName(mainUI)

    def retranslateUi(self, mainUI):
        _translate = QtCore.QCoreApplication.translate
        mainUI.setWindowTitle(_translate("mainUI", "MainWindow"))
        self.yt_push.setText(_translate("mainUI", "YouTube"))
        self.chrome_push.setText(_translate("mainUI", "Chrome"))
        self.word_push.setText(_translate("mainUI", "MS Word"))
        self.power_push.setText(_translate("mainUI", "PowerPoint"))
        self.excel_push.setText(_translate("mainUI", "Excel"))
        self.start_push.setText(_translate("mainUI", "Start"))
        self.close_push.setText(_translate("mainUI", "Close"))
        self.whatsapp_push.setText(_translate("mainUI", "WhatsApp"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainUI = QtWidgets.QMainWindow()
    ui = Ui_mainUI()
    ui.setupUi(mainUI)
    mainUI.show()
    sys.exit(app.exec_())
